# Generated by Django 5.1.3 on 2024-12-11 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_read_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='read_count',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
